### ISSUE TITLE
[BUG]vertex file and the edge file which vid is a string, the final output result of the PR algorithm is wrong

### ISSUE THREAD

**Issue by bitao666** [alibaba/libgrape-lite#45]
When I provide the vertex file and the edge file which vid is a string, the final output result of the PR algorithm is only one vertex, and its PR value is 1, and the vid is not the original id.

**Comment by pwrliang** [comment]
Hi Bitao,

To allow the Pagerank program to accept string type of `oid`, there are a few changes that are needed.

Firstly, the TSVLineParser has a bug that causes the `oid` containing a '\n' character, but I've fixed it within a PR: https://github.com/alibaba/libgrape-lite/pull/46

Secondly, all the examples by default are implemented with numeric `oid`, which means that simply feeding a string id dataset will not work. However, this can be done with few tweaks.
- The type of `oid`, which is the first template parameter of `ImmutableEdgecutFragment` should be changed from `int32_t` to `std::string`
- You may need to specialize a HashPartitioner with `std::string` if you want to use it. Otherwise, SegmentedPartitioner should work without any changes.

The following example demonstrates how to use string as `oid`:

```cpp
void PageRankString(const std::string& efile, const std::string& vfile,
                    const std::string& out_prefix) {
  using GraphType =
      ImmutableEdgecutFragment<std::string, uint32_t, grape::EmptyType,
                               grape::EmptyType, LoadStrategy::kOnlyOut>;
  using AppType = PageRank<GraphType>;
  CommSpec comm_spec;
  auto spec = DefaultParallelEngineSpec();
  double pr_d = 0.85;
  int max_round = 40;

  comm_spec.Init(MPI_COMM_WORLD);

  LoadGraphSpec graph_spec = DefaultLoadGraphSpec();
  graph_spec.set_directed(FLAGS_directed);

  std::shared_ptr<GraphType> fragment =
      LoadGraph<GraphType, SegmentedPartitioner<typename GraphType::oid_t>>(
          efile, vfile, comm_spec, graph_spec);
  auto app = std::make_shared<AppType>();
  auto worker = AppType::CreateWorker(app, fragment);
  worker->Init(comm_spec, spec);
  worker->Query(pr_d, max_round);

  std::ofstream ostream;
  std::string output_path =
      grape::GetResultFilename(out_prefix, fragment->fid());
  ostream.open(output_path);
  worker->Output(ostream);
  ostream.close();
  worker->Finalize();
}
```
